List<Map<String, dynamic>> bikeList = [
  {
    "id": 1,
    "image": "https://ic1.maxabout.us/autos/tw_india/N/2020/5/new-honda-activa-6g-in-matte-axis-grey-color.jpg",
    "image1": "https://images.timesdrive.in/photo/msid-151054462,thumbsize-331211,width-200,height-200,false/151054462.jpg",
    "image2": "https://5.imimg.com/data5/SELLER/Default/2024/9/447984410/FB/XF/PO/103869257/whatsapp-image-2024-09-03-at-2-42-54-pm-500x500.jpeg",
    "image3": "https://imgd.aeplcdn.com/642x361/n/cw/ec/45508/honda-activa-6g-front-right-three-quarter18.jpeg?wm=2&q=75",
    "image4": "https://auto.hindustantimes.com/cms-images/honda_activa6g/images/exterior_honda-activa-6g_left-view_600x400.jpg",
    "name": "Activa 6G",
    "rent": "1200",
    "distance": "1.5 km",
    "rating": 4.4,
    "reviews": "210+",
    "maxSpeed": "85 km/h",
    "mileage": "50 km/l",
    "maxPower": "7.7 bhp",
    "description": "Reliable and smooth scooty ideal for daily commuting in the city.",
    "type": "scooty",
    "maintenance": "Well Maintained",
    "extras": ["Helmet", "Mobile Holder"]
  },
  {
    "id": 2,
    "image": "https://imgd.aeplcdn.com/1056x594/n/ahvh7eb_1768799.jpg?q=80",
    "image1": "https://i.ibb.co/JHddtM3/jupiter1.jpg",
    "image2": "https://i.ibb.co/FWrs4Ch/jupiter2.jpg",
    "image3": "https://i.ibb.co/xjjwLrf/jupiter3.jpg",
    "image4": "https://i.ibb.co/yWjymWm/jupiter4.jpg",
    "name": "TVS Jupiter",
    "rent": "900",
    "distance": "3.2 km",
    "rating": 4.2,
    "reviews": "180+",
    "maxSpeed": "80 km/h",
    "mileage": "50 km/l",
    "maxPower": "7.9 bhp",
    "description": "Comfortable scooty with good mileage and easy handling.",
    "type": "scooty",
    "maintenance": "Recently Serviced",
    "extras": ["Helmet"]
  },
  {
    "id": 3,
    "image": "https://cdn.bikedekho.com/processedimages/suzuki/2025-access-125/source/2025-access-12568314f20a5158.jpg?imwidth=880",
    "image1": "https://i.ibb.co/jyS29VZ/access1.jpg",
    "image2": "https://i.ibb.co/fMS8DMg/access2.jpg",
    "image3": "https://i.ibb.co/5TxGHMH/access3.jpg",
    "image4": "https://i.ibb.co/fq6fsv1/access4.jpg",
    "name": "Access 125",
    "rent": "500",
    "distance": "0.8 km",
    "rating": 4.3,
    "reviews": "160+",
    "maxSpeed": "90 km/h",
    "mileage": "52 km/l",
    "maxPower": "8.7 bhp",
    "description": "Fuel-efficient scooty perfect for quick errands and short trips.",
    "type": "scooty",
    "maintenance": "Well Maintained",
    "extras": ["Helmet", "USB Charger"]
  },
  {
    "id": 4,
    "image": "https://www.yamaha-motor-india.com/theme/v4/images/webp_images/fascino_all/fascino125fi-new/color/Disc/new-blue-s.webp",
    "image1": "https://i.ibb.co/j5GLFbD/fascino1.jpg",
    "image2": "https://i.ibb.co/ykbgDbt/fascino2.jpg",
    "image3": "https://i.ibb.co/zf4CC9j/fascino3.jpg",
    "image4": "https://i.ibb.co/dGwSt8v/fascino4.jpg",
    "name": "Facino",
    "rent": "1000",
    "distance": "2.7 km",
    "rating": 4.1,
    "reviews": "140+",
    "maxSpeed": "90 km/h",
    "mileage": "58 km/l",
    "maxPower": "8.2 bhp",
    "description": "Stylish scooty with great mileage and modern features.",
    "type": "scooty",
    "maintenance": "Excellent Condition",
    "extras": ["Helmet", "Mobile Holder", "USB Charger"]
  },
];
